# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Dewan F. Wahid
title: Data Scientist | Machine Learning
email: dfwahid@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  dewanwahid
googlescholar_username: https://scholar.google.ca/citations?user=B9mXsDgAAAAJ&hl=en
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: dewan-wahid
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Dewan and I'm a professional Data Scientist with 3+ years of industrial experience focused on analyzing data, desiging action-oriented ML models, and delivering data-driven solutions to complex business problems. 
  I have solid academic and practical backgrounds in large-scale optimization, operations research, and network sciences.



content:
  - title: Current Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Programming in Quantum Computing Environmnet from Scratch
        link: github.com/dewanwahid
        # link_text: Project Website
        additional_links:
          - title:  github.com/dewanwahid
            icon: fab fa-github
            url: github.com/dewanwahid
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I am currently learning quantum computing from scratch using the book ["Quantum Computing for Programmers" by Robert Hundt](https://www.cambridge.org/core/books/quantum-computing-for-programmers/BA1C887BE4AC0D0D5653E71FFBEF61C6). 
          Understanding how to design algorithms for quantum computing will be crucial in the near future. 
          I am passionate about learning and applying this cutting-edge technology to solve complex problems.
          I will document my journey in the above git project.

# ![Quantum Computing for Programmers by Robert Hundt](./quntum_book_new.jpg "Quantum Computing for Programmers by Robert Hundt")
  


############# PROFESSIONAL EXPERIENCE ######################
  - title: Professional Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Loblaw Companies Ltd.
        link: loblaw.ca
        # link_text: boringcompany.com
        sub_title: Data Scientist at Marketing Analytics Team
        caption: January 2023 - Present
        quote: >
          "Half the money I spend on advertising is wasted; the problem is I don't know which half." - John Wanamaker (Retail Pioneer)
        description: | # this will include new lines to allow paragraphs
            In my role as a Data Scientist in the Market Analytics team, I excelled in crafting targeted 
            campaign frameworks aimed at achieving maximum return on investment (ROI). Furthermore, 
            I effectively streamlined various frameworks, resulting in a substantial reduction in 
            cloud resource consumption.


      - layout: left
        title: Freshbooks Inc.
        link: freshbooks.com
        # link_text: boringcompany.com
        sub_title: Data Scientist (Mitacs Fellowship Intern)
        caption: September 2019 - July 2022
        quote: >
          "We can't solve problems by using the same kind of thinking we used when we created them." - Albert Einstein (Theoretical Physicist)
        description: | # this will include new lines to allow paragraphs
          I was awarded three consecutive [Mitacs Accelerate Fellowships](https://www.mitacs.ca/our-programs/accelerate-fellowship-professors/), 
          totaling three years, to collaborate with FreshBooks. 
          
          As a Data Scientist (PhD Intern), I conducted in-depth data analysis, developed models to enhance data efficiency, 
          and provided valuable customer insights to guide decision-making. I also designed and implemented fraud detection 
          and invoice categorization frameworks to optimize organizational processes.





############# EDUCATION ####################################
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: McMaster University
        caption: Graduated in 2023
        sub_title: Ph.D. in Computational Science and Engineering
        # quote: >  
        #     "Thesis: Big Data Clustering - Models and Applications"
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          **Thesis:** [Big Data Clustering - Models and Applications](https://macsphere.mcmaster.ca/handle/11375/28504)

          As part of the [Marketing and Supply Chain Analytics (MiSCAN)](https://miscan.mcmaster.ca) Lab and [Professor Elkafi Hassini](https://research.degroote.mcmaster.ca/profiles/profile/?user=hassini)'s research team, my primary research focus was designing heuristic 
          clustering algorithms to identify communities in large-scale empirical networks. 
          During my Ph.D., I had the privilege of receiving three [Mitacs Accelerate Fellowships](https://www.mitacs.ca/our-programs/accelerate-fellowship-students-postdocs) 
          and working with [FreshBooks Inc.](https://www.freshbooks.com) to solve complex business problems. 



      - layout: left
        title: University of British Columbia
        caption: Graduated in 2017
        sub_title: M.Sc. in Computer Science
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          **Thesis:** [Random models and heuristic algorithms for correlation clustering problems on signed social networks](https://open.library.ubc.ca/soa/cIRcle/collections/ubctheses/24/items/1.0347257)

          At UBC, under [Professor Yong Gao](https://cmps.ok.ubc.ca/about/contact/yong-gao/)'s supervision, my research focused on designing random models 
          and analyzing signed-directed social networks. 



      - layout: left
        title: University of Chittagong
        caption: Graduated in 2010
        sub_title: M.S. in Pure Mathematics 
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          **Thesis:** [A Solution Procedure for Minimum Convex-Cost Network Flow Problems](https://arxiv.org/pdf/1210.7260)

          I obtained an one year M.S. degree concentrated in pure mathematics and mathematical optimization. 
      
      - layout: left
        title: University of Chittagong
        caption: Graduated in 2009
        sub_title: B.Sc. in Mathematics
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          In addition to exploring the beautiful and hilly campus of the University of Chittagong, 
          I graduated with a bachelor’s degree in pure mathematics, specializing in fundamental analysis and 
          numerical analysis. These areas of study have helped me refine my analytical 
          and logical skills, which I utilize to solve complex problems in diverse professional 
          environments.


  # - title: A Little More About Me
    # layout: text
    # content: | # this will include new lines to allow paragraphs
    #   Alongside my interests in networks and software engineering some of my other interests and hobbies are:
    #   - Rock climbing
    #   - Gaming
    #   - Knitting
    #   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

    #   Look at this cool image  
    #   ![Trees](./quntum_book.jpg "Trees")




############# RESEARCH EXPR ####################################
  - title: Reseach Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:


      - layout: top-middle
        title: Signed directed random network models
        sub_title: [Code](https://github.com/dewanwahid/random_signed_network)
        # link: [Paper](https://open.library.ubc.ca/soa/cIRcle/collections/ubctheses/24/items/1.0347257)
        link_text: Code
        additional_links:
          - title:  Code
            icon: fab fa-github
            url: github.com/dewanwahid/random_signed_network

          - title: Paper
            icon: fab fa-file-pdf
            url: https://open.library.ubc.ca/soa/cIRcle/collections/ubctheses/24/items/1.0347257

        description: | # this will include new lines to allow paragraphs
          (coming soon!)
  





# ---------- Not after this point
# Footer
footer_show_references: true
# references_title: References on request (Override references text)


# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
