# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Dewan F. Wahid
title: Data Scientist
email: dfwahid@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  dewanwahid
googlescholar_username: https://scholar.google.ca/citations?user=B9mXsDgAAAAJ&hl=en
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: dewan-wahid
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Dewan and I'm a Data Scientist with 3+ years of industrial experience in analyzing data, designing action-oriented ML models and delivering data-driven solutions to complex business problems. 


content:
  - title: Current Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Quantum Computing from Scratch
        link: github.com/dewanwahid
        # link_text: Project Website
        additional_links:
          - title:  github.com/dewanwahid
            icon: fab fa-github
            url: github.com/dewanwahid
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I am currently learning quantum computing from scratch using the book ["Quantum Computing for Programmers" by Robert Hundt](https://www.cambridge.org/core/books/quantum-computing-for-programmers/BA1C887BE4AC0D0D5653E71FFBEF61C6). I believe that understanding how to design algorithms for quantum computing will be crucial in the near future. I am passionate about learning and applying this cutting-edge technology to solve complex problems.

          # [Quantum Computing for Programmers](https://github.com/dewanwahid/dewanwahid.github.io/blob/main/images/quntum_book.jpg)
          - title: 'Bella'
            url: 'https://github.com/dewanwahid/dewanwahid.github.io/blob/main/images/quntum_book.jpg'
            name: 'Quantum Computing for Programmers'
            preview: 'https://github.com/dewanwahid/dewanwahid.github.io/blob/main/images/quntum_book.jpg'
            description: 'Quantum Computing for Programmers'
            cover: './dewanwahid.github.io/blob/main/images/quntum_book.jpg'

############# PROFESSIONAL EXPERIENCE ######################
  - title: Professional Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Loblaw Companies Ltd.
        link: loblaw.ca
        # link_text: boringcompany.com
        sub_title: Data Scientist
        caption: January 2023 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            (coming soon!)




############# EDUCATION ####################################
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: McMaster University
        caption: Graduated in 2023
        sub_title: Ph.D. in Computational Science and Engineering
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          (coming soon!)

      - layout: left
        title: University of British Columbia
        caption: Graduated in 2017
        sub_title: M.Sc. in Computer Science
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          (coming soon!)
      
      - layout: left
        title: University of Chittagon
        caption: Graduated in 2010
        sub_title: M.S. in Mathematics
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          (coming soon!)
      
      - layout: left
        title: University of British Columbia
        caption: Graduated in 2009
        sub_title: B.Sc. in Mathematics
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          (coming soon!)


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
